# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# [START cloudbuild_python_yaml]
# [START cloudbuild_python_dependencies_yaml]
# TEST
steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
# [END cloudbuild_python_dependencies_yaml]

  # [START cloudbuild_python_image_yaml]
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-west1-docker.pkg.dev/$PROJECT_ID/flask-app/flask-app:$COMMIT_SHA', '.']
  # [END cloudbuild_python_image_yaml]

  # [START cloudbuild_python_push_yaml]
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    #args: ['push',  'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/flask-web-app:${SHORT_SHA}']
    args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/flask-app/flask-app:$COMMIT_SHA']
  # [END cloudbuild_python_push_yaml]
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    secretEnv: ['CONNECTION_STRING']
    args: ['-c','sed -i "s,MONGO_CONNECTION_STRING,$$CONNECTION_STRING," kubernetes_private.yaml']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    secretEnv: ['DB_NAME']
    args: ['-c','sed -i "s,MONGO_DB_NAME,$$DB_NAME," kubernetes_private.yaml']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    secretEnv: ['COLLECTION_NAME']
    args: ['-c','sed -i "s,MONGO_COLLECTION_NAME,$$COLLECTION_NAME," kubernetes_private.yaml']
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'set test core image in yamls'
    entrypoint: 'bash'
    args: ['-c','sed -i "s,TEST_IMAGE_NAME,us-west1-docker.pkg.dev/$PROJECT_ID/flask-app/flask-app:$COMMIT_SHA," kubernetes_private.yaml']
  # - name: 'gcr.io/cloud-builders/kubectl'
  #   id: Deploy
  #   args:
  #   - 'apply'
  #   - '-f'
  #   - 'kubernetes.yaml'
  #   env:
  #   - 'CLOUDSDK_COMPUTE_REGION=asia-east1-a'
  #   - 'CLOUDSDK_CONTAINER_CLUSTER=web-app-cluster'
# [END cloudbuild_python_yaml]
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/CONNECTION_STRING/versions/latest
    env: 'CONNECTION_STRING'
  - versionName: projects/$PROJECT_ID/secrets/DB_NAME/versions/latest
    env: 'DB_NAME'
  - versionName: projects/$PROJECT_ID/secrets/COLLECTION_NAME/versions/latest
    env: 'COLLECTION_NAME'